/*
 * Clase que alojará el panel principal y todas las funciones de los botones de la vista
 */

package Main;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Ángel Valera y Pablo Pardo
 */
public class Main extends javax.swing.JFrame {
    

     String ruta="";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
       
       OcultaPaneles();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        nuevoTXT = new javax.swing.JButton();
        nuevoBIN = new javax.swing.JButton();
        nuevoXML = new javax.swing.JButton();
        nuevoJSON = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        nuevaBD = new javax.swing.JButton();
        conectarBD = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        conectarBD1 = new javax.swing.JButton();
        ficheros1 = new accesodom.Ficheros();
        bdPanel1 = new bd.bdPanel();
        eventosPanel1 = new hib.vista.EventosPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        NuevoXML = new javax.swing.JMenuItem();
        NuevoJSON = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        NuevoTexto = new javax.swing.JMenuItem();
        NuevoBinario = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        AbrirXML_DOM = new javax.swing.JMenuItem();
        AbrirXML_JSON = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        AbrirTexto = new javax.swing.JMenuItem();
        AbrirBinario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        CrearNuevaBD = new javax.swing.JMenuItem();
        ConectarBD = new javax.swing.JMenuItem();
        Salir1 = new javax.swing.JMenu();
        ConectarAgenda = new javax.swing.JMenuItem();
        altaUsuario = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jToolBar1.setForeground(new java.awt.Color(238, 238, 238));
        jToolBar1.setRollover(true);
        jToolBar1.setAlignmentX(0.0F);

        nuevoTXT.setForeground(new java.awt.Color(238, 238, 238));
        nuevoTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/txt-icon.png"))); // NOI18N
        nuevoTXT.setToolTipText("Nueva Agenda TXT");
        nuevoTXT.setAlignmentY(0.0F);
        nuevoTXT.setAutoscrolls(true);
        nuevoTXT.setFocusable(false);
        nuevoTXT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoTXT.setIconTextGap(0);
        nuevoTXT.setMaximumSize(new java.awt.Dimension(25, 25));
        nuevoTXT.setMinimumSize(new java.awt.Dimension(25, 25));
        nuevoTXT.setPreferredSize(new java.awt.Dimension(25, 25));
        nuevoTXT.setVerifyInputWhenFocusTarget(false);
        nuevoTXT.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nuevoTXT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTXTActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevoTXT);
        nuevoTXT.getAccessibleContext().setAccessibleDescription("");

        nuevoBIN.setForeground(new java.awt.Color(238, 238, 238));
        nuevoBIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/dat-icon.png"))); // NOI18N
        nuevoBIN.setToolTipText("Nueva Agenda BIN");
        nuevoBIN.setAlignmentY(0.0F);
        nuevoBIN.setAutoscrolls(true);
        nuevoBIN.setFocusable(false);
        nuevoBIN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoBIN.setIconTextGap(0);
        nuevoBIN.setMaximumSize(new java.awt.Dimension(25, 25));
        nuevoBIN.setMinimumSize(new java.awt.Dimension(25, 25));
        nuevoBIN.setPreferredSize(new java.awt.Dimension(25, 25));
        nuevoBIN.setVerifyInputWhenFocusTarget(false);
        nuevoBIN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nuevoBIN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBINActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevoBIN);

        nuevoXML.setForeground(new java.awt.Color(238, 238, 238));
        nuevoXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/File-Adobe-Dreamweaver-XML-01-icon.png"))); // NOI18N
        nuevoXML.setToolTipText("Nueva Agenda XML");
        nuevoXML.setAlignmentY(0.0F);
        nuevoXML.setAutoscrolls(true);
        nuevoXML.setFocusable(false);
        nuevoXML.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoXML.setIconTextGap(0);
        nuevoXML.setMaximumSize(new java.awt.Dimension(25, 25));
        nuevoXML.setMinimumSize(new java.awt.Dimension(25, 25));
        nuevoXML.setPreferredSize(new java.awt.Dimension(25, 25));
        nuevoXML.setVerifyInputWhenFocusTarget(false);
        nuevoXML.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nuevoXML.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoXMLActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevoXML);

        nuevoJSON.setForeground(new java.awt.Color(238, 238, 238));
        nuevoJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/JSON.png"))); // NOI18N
        nuevoJSON.setToolTipText("Nueva Agenda JSON");
        nuevoJSON.setAlignmentY(0.0F);
        nuevoJSON.setAutoscrolls(true);
        nuevoJSON.setFocusable(false);
        nuevoJSON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoJSON.setIconTextGap(0);
        nuevoJSON.setMaximumSize(new java.awt.Dimension(25, 25));
        nuevoJSON.setMinimumSize(new java.awt.Dimension(25, 25));
        nuevoJSON.setPreferredSize(new java.awt.Dimension(25, 25));
        nuevoJSON.setVerifyInputWhenFocusTarget(false);
        nuevoJSON.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nuevoJSON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJSONActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevoJSON);
        jToolBar1.add(jSeparator5);

        nuevaBD.setForeground(new java.awt.Color(238, 238, 238));
        nuevaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Misc-New-Database-icon.png"))); // NOI18N
        nuevaBD.setToolTipText("Nueva Base de datos");
        nuevaBD.setAlignmentY(0.0F);
        nuevaBD.setAutoscrolls(true);
        nuevaBD.setFocusable(false);
        nuevaBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevaBD.setIconTextGap(0);
        nuevaBD.setMaximumSize(new java.awt.Dimension(25, 25));
        nuevaBD.setMinimumSize(new java.awt.Dimension(25, 25));
        nuevaBD.setPreferredSize(new java.awt.Dimension(25, 25));
        nuevaBD.setVerifyInputWhenFocusTarget(false);
        nuevaBD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nuevaBD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaBDActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevaBD);

        conectarBD.setForeground(new java.awt.Color(238, 238, 238));
        conectarBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Places-network-server-database-icon.png"))); // NOI18N
        conectarBD.setToolTipText("Abrir Base de Datos");
        conectarBD.setAlignmentY(0.0F);
        conectarBD.setAutoscrolls(true);
        conectarBD.setFocusable(false);
        conectarBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conectarBD.setIconTextGap(0);
        conectarBD.setMaximumSize(new java.awt.Dimension(25, 25));
        conectarBD.setMinimumSize(new java.awt.Dimension(25, 25));
        conectarBD.setPreferredSize(new java.awt.Dimension(25, 25));
        conectarBD.setVerifyInputWhenFocusTarget(false);
        conectarBD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        conectarBD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conectarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarBDActionPerformed(evt);
            }
        });
        jToolBar1.add(conectarBD);
        jToolBar1.add(jSeparator6);

        conectarBD1.setForeground(new java.awt.Color(238, 238, 238));
        conectarBD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/User-Interface-Exit-icon.png"))); // NOI18N
        conectarBD1.setToolTipText("Abrir Base de Datos");
        conectarBD1.setAlignmentY(0.0F);
        conectarBD1.setAutoscrolls(true);
        conectarBD1.setFocusable(false);
        conectarBD1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conectarBD1.setIconTextGap(0);
        conectarBD1.setMaximumSize(new java.awt.Dimension(25, 25));
        conectarBD1.setMinimumSize(new java.awt.Dimension(25, 25));
        conectarBD1.setPreferredSize(new java.awt.Dimension(25, 25));
        conectarBD1.setVerifyInputWhenFocusTarget(false);
        conectarBD1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        conectarBD1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conectarBD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarBD1ActionPerformed(evt);
            }
        });
        jToolBar1.add(conectarBD1);

        bdPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        bdPanel1.setMinimumSize(new java.awt.Dimension(800, 467));
        bdPanel1.setName(""); // NOI18N
        bdPanel1.setOpaque(false);
        bdPanel1.setPreferredSize(new java.awt.Dimension(800, 473));

        eventosPanel1.setPreferredSize(new java.awt.Dimension(800, 499));

        jMenu4.setText("Ficheros");

        jMenu2.setText("Nuevo");

        NuevoXML.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        NuevoXML.setText("Fichero XML");
        NuevoXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoXMLActionPerformed(evt);
            }
        });
        jMenu2.add(NuevoXML);

        NuevoJSON.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        NuevoJSON.setText("Fichero JSON");
        NuevoJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoJSONActionPerformed(evt);
            }
        });
        jMenu2.add(NuevoJSON);
        jMenu2.add(jSeparator2);

        NuevoTexto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        NuevoTexto.setText("Fichero Texto");
        NuevoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoTextoActionPerformed(evt);
            }
        });
        jMenu2.add(NuevoTexto);

        NuevoBinario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        NuevoBinario.setText("Fichero Binario");
        NuevoBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoBinarioActionPerformed(evt);
            }
        });
        jMenu2.add(NuevoBinario);

        jMenu4.add(jMenu2);
        jMenu4.add(jSeparator3);

        jMenu3.setText("Abrir");

        AbrirXML_DOM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        AbrirXML_DOM.setText("Fichero XML");
        AbrirXML_DOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirXML_DOMActionPerformed(evt);
            }
        });
        jMenu3.add(AbrirXML_DOM);

        AbrirXML_JSON.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        AbrirXML_JSON.setText("Fichero JSON");
        AbrirXML_JSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirXML_JSONActionPerformed(evt);
            }
        });
        jMenu3.add(AbrirXML_JSON);
        jMenu3.add(jSeparator1);

        AbrirTexto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        AbrirTexto.setText("Abrir Fich. Texto");
        AbrirTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirTextoActionPerformed(evt);
            }
        });
        jMenu3.add(AbrirTexto);

        AbrirBinario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        AbrirBinario.setText("Abrir Fich. Binario");
        AbrirBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirBinarioActionPerformed(evt);
            }
        });
        jMenu3.add(AbrirBinario);

        jMenu4.add(jMenu3);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("BD");

        CrearNuevaBD.setText("Crear");
        CrearNuevaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearNuevaBDActionPerformed(evt);
            }
        });
        jMenu1.add(CrearNuevaBD);

        ConectarBD.setText("Conectar");
        ConectarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarBDActionPerformed(evt);
            }
        });
        jMenu1.add(ConectarBD);

        jMenuBar1.add(jMenu1);

        Salir1.setText("Eventos");
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });

        ConectarAgenda.setText("Conectar");
        ConectarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarAgendaActionPerformed(evt);
            }
        });
        Salir1.add(ConectarAgenda);

        altaUsuario.setText("Alta Usuario");
        altaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaUsuarioActionPerformed(evt);
            }
        });
        Salir1.add(altaUsuario);

        jMenuBar1.add(Salir1);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(eventosPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ficheros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ficheros1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventosPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     /**
    *
    * Método para ocultar los paneles de nuestro programa:
    * 
    */
    private void OcultaPaneles(){
       ficheros1.setVisible(false);
       bdPanel1.setVisible(false);
      eventosPanel1.setVisible(false);
       
     
    }
    
    /**
    *
    * Método para crear un nuevo XML:
    * 
    */
    private void NuevoXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoXMLActionPerformed
         OcultaPaneles();
        ficheros1.setVisible(true);
        ficheros1.nuevoArchivo = 1;
        ficheros1.tipoArchivo = 1;
        ficheros1.gesDOM.setContenidoXML("");
        ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.xml");
        ficheros1.jButtonGUARDAXML().setEnabled(false);
        ficheros1.getjTextAreaDOM().setText("");
        ficheros1.getjTextAreaDOM().setEnabled(false);
        ficheros1.ActivarCampos();
    }//GEN-LAST:event_NuevoXMLActionPerformed

    /**
    *
    * Método para crear un nuevo JSON:
    * 
    */
    private void NuevoJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoJSONActionPerformed
         OcultaPaneles();
        ficheros1.setVisible(true);
        ficheros1.nuevoArchivo = 2;
        ficheros1.tipoArchivo = 2;
        ficheros1.gesJSON.setContenidoJSON("");
        ficheros1.gesJSON.setTextoJSON("[]");
        ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.json");
        ficheros1.jButtonGUARDAXML().setEnabled(false);
        ficheros1.getjTextAreaDOM().setText("");
        ficheros1.getjTextAreaDOM().setEnabled(false);
        ficheros1.ActivarCampos();
    }//GEN-LAST:event_NuevoJSONActionPerformed

    /**
    *
    * Método para crear un nuevo TXT:
    * 
    */
    private void NuevoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoTextoActionPerformed
         OcultaPaneles();
        ficheros1.setVisible(true);
        ficheros1.nuevoArchivo = 3;
        ficheros1.tipoArchivo = 3;
        ficheros1.gesTXT.setContenidoTXT("");
        ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.txt");
        ficheros1.jButtonGUARDAXML().setEnabled(false);
        ficheros1.getjTextAreaDOM().setText("");
        ficheros1.getjTextAreaDOM().setEnabled(false);
        ficheros1.ActivarCampos();
    }//GEN-LAST:event_NuevoTextoActionPerformed

    /**
    *
    * Método para crear un nuevo Binario:
    * 
    */
    private void NuevoBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoBinarioActionPerformed
         OcultaPaneles();
        ficheros1.setVisible(true);
        ficheros1.nuevoArchivo = 4;
        ficheros1.tipoArchivo = 4;
        ficheros1.gesBIN.setContenidoBIN("");
        ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.bin");
        ficheros1.jButtonGUARDAXML().setEnabled(false);
        ficheros1.getjTextAreaDOM().setText("");
        ficheros1.getjTextAreaDOM().setEnabled(false);
        ficheros1.ActivarCampos();
    }//GEN-LAST:event_NuevoBinarioActionPerformed

    /**
    *
    * Método para abrir un XML:
    * 
    */
    private void AbrirXML_DOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirXML_DOMActionPerformed
         OcultaPaneles(); 
        ficheros1.setVisible(true);
        if (ficheros1.gesDOM.abrir_XML_DOM(ficheros1.dialogoSeleccionTipoRecurso()) == false) {
            ficheros1.jLabelmensaje().setText("Error al crear el objeto DOM");
            ficheros1.jButtonAnyadir.setEnabled(true);

            System.out.println("Error al crear el objeto DOM");
        } else {
            ficheros1.tipoArchivo = 1;
            ficheros1.jLabelmensaje().setText("¡Ya se ha abierto el archivo para XML!");
            ficheros1.jButtonAnyadir.setEnabled(true);
            ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.xml");
             ficheros1.jButtonJSON().setEnabled(true);
            ficheros1.jPanelDatos().setEnabled(true);
            System.out.println("¡Ya se ha abierto el archivo para XML!");
        }
    }//GEN-LAST:event_AbrirXML_DOMActionPerformed

    /**
    *
    * Método para abrir un JSON:
    * 
    */
    private void AbrirXML_JSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirXML_JSONActionPerformed
         OcultaPaneles(); 
        ficheros1.setVisible(true);
        if (ficheros1.gesJSON.abrirJSON(ficheros1.dialogoSeleccionTipoRecurso()) == false) {
            ficheros1.jLabelmensaje().setText("Error al abrir el archivo para SAX");
            ficheros1.jPanelDatos().setEnabled(false);
            System.out.println("Error al abrir el archivo para SAX");
        } else {
            ficheros1.tipoArchivo = 2;
            ficheros1.jLabelmensaje().setText("¡Ya se ha abierto el archivo para JSON!");
            ficheros1.jButtonJSON().setEnabled(true);
            ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.json");

            ficheros1.jPanelDatos().setEnabled(true);
            System.out.println("¡Ya se ha abierto el archivo para JSON!");
        }
    }//GEN-LAST:event_AbrirXML_JSONActionPerformed

    /**
    *
    * Método para abrir un TXT:
    * 
    */
    private void AbrirTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirTextoActionPerformed
         OcultaPaneles(); 
        ficheros1.setVisible(true);
        if (ficheros1.gesTXT.abrir_TXT(ficheros1.dialogoSeleccionTipoRecurso()) == false) {
            ficheros1.jLabelmensaje().setText("Error al abrir el archivo TXT");
            ficheros1.jButtonJSON().setEnabled(false);
            System.out.println("Error al abrir el archivo TXT");
        } else {
            ficheros1.tipoArchivo = 3;
            ficheros1.jLabelmensaje().setText("¡Ya se ha abierto el archivo de Texto!");
            ficheros1.jButtonJSON().setEnabled(true);

            ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.txt");

            ficheros1.jPanelDatos().setEnabled(true);
            System.out.println("¡Ya se ha abierto el archivo TXT!");
        }
    }//GEN-LAST:event_AbrirTextoActionPerformed

    /**
    *
    * Método para abrir un Binario:
    * 
    */
    private void AbrirBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirBinarioActionPerformed
         OcultaPaneles(); 
        ficheros1.setVisible(true);
        if (ficheros1.gesBIN.abrirBIN(ficheros1.dialogoSeleccionTipoRecurso()) == false) {
            ficheros1.jLabelmensaje().setText("Error al abrir el archivo DAT");
            ficheros1.jButtonJSON().setEnabled(false);
            System.out.println("Error al abrir el archivo TXT");
        } else {
            ficheros1.tipoArchivo = 4;
            ficheros1.jLabelmensaje().setText("¡Ya se ha abierto el archivo binario!");
            ficheros1.jButtonJSON().setEnabled(true);

            ficheros1.jButtonGUARDAXML().setText("Guardar como archivo salida.dat");

            ficheros1.jPanelDatos().setEnabled(true);
            System.out.println("¡Ya se ha abierto el archivo binario!");
        }
    }//GEN-LAST:event_AbrirBinarioActionPerformed

    /**
    *
    * Método para salir de nuestra aplicación:
    * 
    */
    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked
 
    /**
    *
    * Método para crear una nueva Base de Datos SQLite:
    * 
    */
    private void CrearNuevaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearNuevaBDActionPerformed
         OcultaPaneles();
        //bdPanel1.setVisible(true);
    
        this.bdPanel1.CrearBD.setVisible(true);
        this.bdPanel1.CrearBD.setEnabled(true);
    }//GEN-LAST:event_CrearNuevaBDActionPerformed

    /**
    *
    * Método para conectar una Base de Datos SQLite:
    * 
    */
    private void ConectarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarBDActionPerformed
      
       ruta= bdPanel1.dialogoSeleccionTipoRecurso().getAbsolutePath();
       bdPanel1.conectarbd(ruta); 
    }//GEN-LAST:event_ConectarBDActionPerformed

     private void EventosActionPerformed(java.awt.event.ActionEvent evt) {                                           
      
      OcultaPaneles();
            
          
       
    }   
    
    private void nuevoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTXTActionPerformed
        this.NuevoTextoActionPerformed(evt);
    }//GEN-LAST:event_nuevoTXTActionPerformed

    private void nuevoBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBINActionPerformed
        this.NuevoBinarioActionPerformed(evt);
        
    }//GEN-LAST:event_nuevoBINActionPerformed

    private void nuevoXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoXMLActionPerformed
        this.NuevoXMLActionPerformed(evt);
    }//GEN-LAST:event_nuevoXMLActionPerformed

    private void nuevoJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJSONActionPerformed
       this.NuevoJSONActionPerformed(evt);
    }//GEN-LAST:event_nuevoJSONActionPerformed

    private void nuevaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaBDActionPerformed
       this.CrearNuevaBDActionPerformed(evt);
    }//GEN-LAST:event_nuevaBDActionPerformed

    private void conectarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarBDActionPerformed
       this.ConectarBDActionPerformed(evt);
    }//GEN-LAST:event_conectarBDActionPerformed

    private void conectarBD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarBD1ActionPerformed
      this.SalirMouseClicked(null);
    }//GEN-LAST:event_conectarBD1ActionPerformed

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
    //   this.OcultaPaneles();
     //  this.eventosPanel1.setVisible(true);
    }//GEN-LAST:event_Salir1MouseClicked

    private void ConectarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarAgendaActionPerformed
        // TODO add your handling code here:
     //   this.
        this.OcultaPaneles();
        this.eventosPanel1.setVisible(false);
        this.eventosPanel1.Login.setVisible(true);
    }//GEN-LAST:event_ConectarAgendaActionPerformed

    private void altaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuarioActionPerformed
        this.OcultaPaneles();
        this.eventosPanel1.setVisible(false);
        this.eventosPanel1.panelAltaUsuario.setVisible(true);
        //this.eventosPanel1.Login.setVisible(true);
    }//GEN-LAST:event_altaUsuarioActionPerformed

      

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirBinario;
    private javax.swing.JMenuItem AbrirTexto;
    private javax.swing.JMenuItem AbrirXML_DOM;
    private javax.swing.JMenuItem AbrirXML_JSON;
    private javax.swing.JMenuItem ConectarAgenda;
    private javax.swing.JMenuItem ConectarBD;
    private javax.swing.JMenuItem CrearNuevaBD;
    private javax.swing.JMenuItem NuevoBinario;
    private javax.swing.JMenuItem NuevoJSON;
    private javax.swing.JMenuItem NuevoTexto;
    private javax.swing.JMenuItem NuevoXML;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenu Salir1;
    private javax.swing.JMenuItem altaUsuario;
    private bd.bdPanel bdPanel1;
    private javax.swing.JButton conectarBD;
    private javax.swing.JButton conectarBD1;
    private hib.vista.EventosPanel eventosPanel1;
    private accesodom.Ficheros ficheros1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton nuevaBD;
    private javax.swing.JButton nuevoBIN;
    private javax.swing.JButton nuevoJSON;
    private javax.swing.JButton nuevoTXT;
    private javax.swing.JButton nuevoXML;
    // End of variables declaration//GEN-END:variables
}
